/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.data;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Misbahul Munir
 */
public class ManajemenNasabahFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManajemenNasabahFrame
     */
    public ManajemenNasabahFrame() {
        initComponents();
        tanggalSekarang();
        windowOpened();

    }

    /*
    Method menampilkan tanggal
     */
    private void tanggalSekarang() {
        Locale local = new Locale("id", "ID");
        Locale.setDefault(local);
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat formatTanggal = new java.text.SimpleDateFormat("EEEEE, dd MMMMM yyyy");
        tanggalLabel.setText(formatTanggal.format(sekarang));
    }

    /*
    Method windowOpened dan tombol reset data
     */
    private void windowOpened() {
        tabelNasabah.setEnabled(false);
        idTextField.setEnabled(false);
        cariTextField.setEnabled(false);
        nameTextField.setEnabled(false);
        genderComboBox.setEnabled(false);
        ageTextField.setEnabled(false);
        marriedCheckBox.setEnabled(false);
        noHpTextField.setEnabled(false);
        teleponTextField.setEnabled(false);
        alamatTextArea.setEnabled(false);
        resetButton.setEnabled(false);
        reloadButton.setEnabled(true);
        
        idTextField.setText("");
        cariTextField.setText("");
        nameTextField.setText("");
        genderComboBox.setSelectedItem("Male");
        ageTextField.setText("");
        marriedCheckBox.setSelected(false);
        noHpTextField.setText("");
        teleponTextField.setText("");
        alamatTextArea.setText("");

        DefaultTableModel model = (DefaultTableModel) tabelNasabah.getModel();
        model.getDataVector().removeAllElements();
        tabelNasabah.setModel(model);
        settingUkuranTabel(tabelNasabah, new int[]{130, 450});
    }

    /*
    Method setting ukutan kolom tabel
     */
    private void settingUkuranTabel(javax.swing.JTable tabel, int lebar[]) {
        tabel.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int kolom = tabel.getColumnCount();
        for (int i = 0; i < kolom; i++) {
            javax.swing.table.TableColumn kolomTabel = tabel.getColumnModel().getColumn(i);
            kolomTabel.setPreferredWidth(lebar[i]);
            tabel.setRowHeight(24);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        marriedCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelNasabah = new javax.swing.JTable();
        reloadButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        noHpTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        teleponTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        cariTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tanggalLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Manajemen Nasabah");
        setResizable(false);

        marriedCheckBox.setText("Married");

        jLabel6.setText("Age");

        tabelNasabah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Nasabah", "Nama Nasabah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelNasabah);

        reloadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/gambar/Preview_16x16.png"))); // NOI18N
        reloadButton.setText("Reload Data");
        reloadButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/gambar/Check_16x16.png"))); // NOI18N
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel3.setText("Gender");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel8.setText("No Hp");

        jLabel9.setText("Phone");

        jLabel5.setText("Address");

        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        jScrollPane2.setViewportView(alamatTextArea);

        jLabel4.setText("ID Nasabah");

        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTextFieldKeyReleased(evt);
            }
        });

        cariTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariTextFieldKeyReleased(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/gambar/Find_16x16.png"))); // NOI18N
        jLabel7.setText("Search Data Nasabah");

        jLabel10.setText("Detail");

        jLabel19.setFont(new java.awt.Font("PhrasticMedium", 0, 18)); // NOI18N
        jLabel19.setText("Manajemen Nasabah");

        tanggalLabel.setText("Tanggal");

        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/gambar/Cancel_16x16.png"))); // NOI18N
        resetButton.setText("Reset Data");
        resetButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/gambar/Delete_16x16.png"))); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tanggalLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(marriedCheckBox))
                                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(teleponTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noHpTextField))
                                .addGap(8, 8, 8))
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reloadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tanggalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reloadButton)
                    .addComponent(jLabel7)
                    .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(noHpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marriedCheckBox)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showPeople() {
        DefaultTableModel model = (DefaultTableModel) tabelNasabah.getModel();
        List<DataNasabah> dataNasabah = getDataFromFile("C:\\JAVA_LATIHAN\\ManajemenNasabah.txt");

        Object[] row = new Object[2];
        for (DataNasabah dNasabah : dataNasabah) {
            row[0] = dNasabah.getKode();
            row[1] = dNasabah.getName();
            model.addRow(row);
        }

        ListSelectionModel rowModel = tabelNasabah.getSelectionModel();
        rowModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int i = tabelNasabah.getSelectedRow();
                    String id = (String) model.getValueAt(i, 0);//ambil velue row i 
                    idTextField.setText(id);
                    String nama = (String) model.getValueAt(i, 1);//ambil velue row i 
                    nameTextField.setText(nama);
                    String gender = dataNasabah.get(i).getGender();
                    genderComboBox.setSelectedItem(gender);
                    Boolean maried = dataNasabah.get(i).getMarried();
                    marriedCheckBox.setSelected(maried);
                    Integer age = dataNasabah.get(i).getAge();
                    String umur = String.valueOf(age);
                    ageTextField.setText(umur);
                    noHpTextField.setText(dataNasabah.get(i).getNoHpNasabah());
                    teleponTextField.setText(dataNasabah.get(i).getNoTeleponNasabah());
                    alamatTextArea.setText(dataNasabah.get(i).getAlamatNasabah());

                    System.out.println("row dipilih");
                }
            }
        });

    }

    private List<DataNasabah> getDataFromFile(String filename) {
        FileReader fileReader = null;
        try {
            List<DataNasabah> dataNasabah = new ArrayList<>();
            File file = new File(filename);
            fileReader = new FileReader(file); //mencari file
            BufferedReader reader = new BufferedReader(fileReader);// untuk memanggil filereader/membaca file
            String line = null;
            while ((line = reader.readLine()) != null) {
                System.out.println(line);
                //Split line assign ke strig array
                String[] splitLine = line.split(",");
                //buat objek questionmodel, array idx 0 kata dasar, idx 1 untuk petunjuk
                DataNasabah wm = new DataNasabah(splitLine[0], splitLine[1].trim(), splitLine[2].trim(), Boolean.parseBoolean(splitLine[3].trim()), Integer.parseInt(splitLine[4].trim()), splitLine[5].trim(), splitLine[6].trim(), splitLine[7].trim());
                // add ke question collection
                dataNasabah.add(wm);
            }
            Collections.sort(dataNasabah);
            //periksa ukuran question
            System.out.println("\nJumlah Pertanyaan Dalam Collection : " + dataNasabah.size() + "\n");
            return dataNasabah;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("File Tidak Ditemukan");
        } catch (IOException ex) {
            Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Kemungkinan File Rusak");
        } finally {
            try {
                fileReader.close();
            } catch (IOException ex) {
                Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return null;
    }

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        // TODO add your handling code here:
        showPeople();
        tabelNasabah.setEnabled(true);
        cariTextField.setEnabled(true);
        reloadButton.setEnabled(false);
        resetButton.setEnabled(true);
    }//GEN-LAST:event_reloadButtonActionPerformed

    private void idTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextFieldKeyReleased
        // TODO add your handling code here:               
    }//GEN-LAST:event_idTextFieldKeyReleased

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed


    private void cariTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTextFieldKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelNasabah.getModel();
        String search = cariTextField.getText().toLowerCase();
        TableRowSorter<TableModel> ts = new TableRowSorter<>(model);
        tabelNasabah.setRowSorter(ts);
        ts.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_cariTextFieldKeyReleased

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        windowOpened();
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManajemenNasabahFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JTextField cariTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox marriedCheckBox;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField noHpTextField;
    private javax.swing.JButton reloadButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JTable tabelNasabah;
    private javax.swing.JLabel tanggalLabel;
    private javax.swing.JTextField teleponTextField;
    // End of variables declaration//GEN-END:variables
}
